modLoader="javafml"
loaderVersion="[28,)"
license="MIT"

logoFile=""
[[mods]]
modId="compmod"
version="1.20.1"
displayName="Sho'compMod"
displayURL=""
updateJSONURL=""
credits=""
authors=""
description = """
機能：(20250502)
・1/4ブロックの追加
・隣接ブロックと接続しない塀ブロックの追加
・ワールドセーブ時に外部スクリプトを起動する機能
"""
